iduo.Screen/Models/Notice.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace iduo.Screen.Models
{
    /// <summary>
    /// 新闻
    /// </summary>
    public class Notice
    {
        /// <summary>
        /// 获取或设置 新闻的ID
        /// </summary>
        public string id { get; set; }
        /// <summary>
        /// 获取或设置 新闻标题
        /// </summary>
        public string title { get; set; }
        /// <summary>
        ///获取或设置  新闻内容
        /// </summary>
        public string content { get; set; }
        /// <summary>
        /// 获取或设置 新闻的作者
        /// </summary>
        public string author { get; set; }
        /// <summary>
        /// 获取或设置 新闻的时间
        /// </summary>
        public string time { get; set; }
        /// <summary>
        /// 获取或设置 时间
        /// </summary>
        public DateTime DateTime { get; set; }
        /// <summary>
        /// 获取或设置 Url
        /// </summary>
        public string url { get; set; }

        public string Ext01 { get; set; }
        public string Ext02 { get; set; }
        public string Ext03 { get; set; }
        public string Ext04 { get; set; }
        public string Ext05 { get; set; }



    }

    /// <summary>
    /// 新闻数量
    /// </summary>
    public class NoticeCount
    {
        public string num { get; set; }
    }
}

iduo.Screen/Controllers/NoticeController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web.Mvc;
using iduo.Screen.Common;
using iduo.Screen.Models;

namespace iduo.Screen.Controllers
{
    public class NoticeController : Controller
    {
        //新闻数量Url
        private static string newsCountUrl = ConfigurationManager.AppSettings["iduo.screen.newscount"];
        //新闻Url
        private static string newsUrl = ConfigurationManager.AppSettings["iduo.screen.news"];
        //新闻数量
        private static string newsCountJson { get; set; }
        private static string noticeJson { get; set; }



        /// <summary>
        /// 新闻列表
        /// </summary>
        /// <param name="newsType">1=教学通知 2=教学动态 3=讲座预告</param>
        /// <param name="size">数量</param>
        /// <param name="page">页码</param>
        /// <returns></returns>
        public ActionResult Index(int newsType=0, int size = 10, int page = 1)
        {
            try
            {
                var title = "";
                List<Notice> formatNotices = new List<Notice>();
                if (newsType!=0) {
                    //获取新闻
                    if (!string.IsNullOrEmpty(newsUrl))
                        noticeJson = Common.Common.GetNotice(newsUrl, "", newsType, size, page);

                    //获取新闻数数量
                    if (!string.IsNullOrEmpty(newsCountUrl))
                        newsCountJson = Common.Common.GetNoticeCount(newsCountUrl, newsType);

                    //新闻
                    formatNotices = Common.Common.FormatNotice(noticeJson);
                    //新闻数量
                    List<NoticeCount> formatNoticeCount = Common.Common.FormatNoticeCount(newsCountJson);

                    var newsCount = formatNoticeCount.FirstOrDefault();

                    switch (newsType)
                    {
                        case 1:
                            title = "教学通知";
                            break;
                        case 2:
                            title = "教学动态";
                            break;
                        case 3:
                            title = "讲座预告";
                            break;
                    }
                }

             
                ViewBag.title = title;
                ViewBag.notices = formatNotices;
                ViewBag.page = page;
                ViewBag.size = size;
                ViewBag.newsType = newsType;
                ViewBag.newsCount = formatNotices == null ? 0 : formatNotices.Count();
            }
            catch (Exception ex)
            {

                throw;
            }
         

            return View();
        }
    }
}

iduo.Screen/Views/Notice/Index.cshtml
@using iduo.Screen.Models
@{
    Layout = null;
    //新闻
    var notices = ViewBag.notices as List<Notice>;
    var newsCount = ViewBag.newsCount;
    var page = ViewBag.page;
    var size = ViewBag.size;
    var newsType = ViewBag.newsType;

}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.title</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/AdminLTE-2.3.11/dist/css/AdminLTE.css" rel="stylesheet" />
    <script src="~/Scripts/jquery/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap/bootstrap.js"></script>

    <style>
        body {
            font-family: "Microsoft YaHei"!important;
        }
        .col-xs-6 {
            margin-left: 22%;
            margin-top: 3%;
        }
        .a-notice-list {
            display: block;
            width: 100%;
            height: 16px;
            margin-top: 18px;
            float: left;
        }
        .div-poiont {
            float: left;
            width: 4px;
            height: 4px;
            background: #cfac62;
            margin-top: 5px;
            overflow: hidden;
            zoom: 1;
        }
        .div-notice-title {
            float: left;
            line-height: 16px;
            width: 515px;
            height: 16px;
            text-align: left;
            margin-left: 15px;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
            color: #414141;
            font-size: 14px;
        }
        .div-notice-date {
            float: right;
            color: #7c7c7c;
            line-height: 16px;
            font-size: 12px;
            margin-right: 1%;
        }
        a:hover {
            color: #e58d1d !important;
            text-decoration: none;
        }
        a {
            text-decoration: none;
        }
    </style>
    <style>
        .close {
            float: inherit !important;
            position: relative;
            display: inline-block;
            width: 100px;
            height: 100px;
            overflow: hidden;
            border-radius: 50px;
            background: black;
            opacity: 0.5;
        }

            .close:hover {
                cursor: pointer;
                opacity: 1;
            }

            /*.close::before, .close::after {
                  content: '';
                  position: absolute;
                  width: 80%;
                  top: 50%;
                  left: 10%;
                  height: 12px;
                  margin-top: -6px;
                  border-radius: 5px;
                  background: #ffffff;
              }*/

            .close::before {
                transform: rotate(45deg);
            }

            .close::after {
                transform: rotate(-45deg);
            }
        .custom-close {
            float: inherit !important;
            position: relative;
            display: inline-block;
            width: 100px;
            overflow: hidden;
            background: #999;
            opacity: 0.5;
        }
        .bottomDiv {
            position: fixed;
            height: 100px;
            line-height: 100px;
            text-align: center;
            background-color: rgba(255, 255, 255, 0.15);
            bottom: 15%;
            _position: absolute;
            width: 100%;
        }

        .back-span {
            margin-top: 35% !important;
            color: white;
            position: absolute;
            left: 24px;
            font-size: 28px;
        }

        .custom-botton {
            width: 150px;
            color: white;
            margin-top: 3%;
            font-size: 30px;
        }
    </style>

</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-6">
                <div class="box box-success">

                    <div class="box-header">
                        <h3 class="box-title">@ViewBag.title</h3>
                    </div>

                    <div class="box-body no-padding">

                        @if (notices != null)
                        {
                            foreach (var item in notices)
                            {
                                <a class="a-notice-list" href="@item.url" target="_blank" id="@item.id">
                                    <div class="div-poiont"></div>
                                    <span class="div-notice-title">@item.title</span>
                                    <span class="div-notice-date">@item.time</span>
                                </a>
                            }
                        }

                    </div>

                    <div class="box-footer clearfix">
                        <ul class="pagination no-margin pull-right">
                            @if (newsCount != null || newsCount > 0)
                            {
                                if (page == 1)
                                {
                                    <li class="disabled"><a>«</a></li>
                                }
                                else
                                {
                                    <li><a href="@Url.Action("Index","Notice",new {newsType=@newsType,size=@size,page=(@page-1) })">«</a></li>
                                }
                                <li><a>第@(page)页</a></li>
                                if (notices.Count() > 0)
                                {
                                    <li><a href="@Url.Action("Index","Notice",new {newsType=@newsType,size=@size,page=(@page+1) })">»</a></li>
                                }
                                else
                                {
                                    <li class="disabled"><a>»</a></li>
                                }
                            }

                            
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        @*<div class="bottomDiv"><a href="javascript:window.opener=null;window.open('','_self');window.close();" class="close"><span class="back-span">返回</span></a></div>*@
        <div class="bottomDiv"><a href="javascript:window.opener=null;window.open('','_self');window.close();" class="btn  btn-lg custom-botton custom-close" onclick="CloseWin()">返回</a></div>

    </div>
</body>

</html>
<script type="text/javascript">

    $(document).ready(function () {

        var screenWidth = $(window).width();//获取屏幕可视区域的宽度。
        $(".bottomDiv").width(screenWidth);//将宽度赋值给bottomDiv使其可以贯穿整个屏幕。
        var screenHeight = $(window).height();//获取屏幕可视区域的高度。
        var divHeight = $(".bottomDiv").height() + 1;//bottomDiv的高度再加上它一像素的边框。

        $(window).scroll(function () {
            var scrollHeight = $(document).scrollTop();//获取滚动条滚动的高度。
            if (!window.XMLHttpRequest) {
                $(".bottomDiv").css("top", screenHeight + scrollHeight - divHeight);
            }//判断是否为IE6，如果是，执行大括号中内容
        })

    })
</script>